In [2]:
import numpy as np

In [3]:
arr=np.array([1,23,45])

In [4]:
arr

array([ 1, 23, 45])

In [5]:
arr2=np.array([[1,34,23],[56,3,55]])

In [6]:
arr2

array([[ 1, 34, 23],
       [56,  3, 55]])

In [7]:
arr2.ndim

2

In [8]:
arr3=np.array([[1,34,23],[56,3,55],[77,98,6],[24,55,44],[32,66,11],[98,33,44]])

In [9]:
arr3

array([[ 1, 34, 23],
       [56,  3, 55],
       [77, 98,  6],
       [24, 55, 44],
       [32, 66, 11],
       [98, 33, 44]])

In [10]:
arr3.ndim

2

In [11]:
arr4=np.array([[[1,23,33],[2,22,54],[5,6,8]],[[10,20,30],[25,22,55],[50,60,80]]])

In [12]:
arr4

array([[[ 1, 23, 33],
        [ 2, 22, 54],
        [ 5,  6,  8]],

       [[10, 20, 30],
        [25, 22, 55],
        [50, 60, 80]]])

In [13]:
arr4.ndim

3

In [14]:
arr2[0,2]

23

In [15]:
arr2[1,0:2]

array([56,  3])

In [16]:
arr4[0,1,2]

54

In [17]:
arr4[1,1,1:3]

array([22, 55])

In [18]:
arr4.shape

(2, 3, 3)

In [19]:
temperature_data = [25.3, 26.1, 24.8, 23.5, 27.2]
pressure_data = [101.2, 100.8, 101.5, 100.2, 101.0]
humidity_data = [55.2, 54.8, 56.5, 53.7, 55.9]

In [20]:
temparr=np.array(temperature_data)
pressarr=np.array(pressure_data)
humarr=np.array(humidity_data)

In [21]:
tempmean=np.mean(temparr)

In [22]:
tempmean

25.380000000000003

In [23]:
tempmin=np.mean(temparr)

In [24]:
tempmin

25.380000000000003